# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/enocean.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protos/enocean.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/enocean.proto\x12\taruba.iot\"\xa3\x03\n\rEnOceanPacket\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0c\n\x04rssi\x18\x03 \x01(\x05\x12\x0b\n\x03\x65\x65p\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\t\x12\x13\n\x06\x61p_mac\x18\x06 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65vice_name\x18\x07 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08\x64istance\x18\x08 \x01(\x02H\x02\x88\x01\x01\x12\x18\n\x0btemperature\x18\t \x01(\x02H\x03\x88\x01\x01\x12\x15\n\x08humidity\x18\n \x01(\x02H\x04\x88\x01\x01\x12\x1a\n\rcontact_state\x18\x0b \x01(\x08H\x05\x88\x01\x01\x12\x18\n\x0billuminance\x18\x0c \x01(\x02H\x06\x88\x01\x01\x12\x1a\n\rbattery_level\x18\r \x01(\x02H\x07\x88\x01\x01\x42\t\n\x07_ap_macB\x0e\n\x0c_device_nameB\x0b\n\t_distanceB\x0e\n\x0c_temperatureB\x0b\n\t_humidityB\x10\n\x0e_contact_stateB\x0e\n\x0c_illuminanceB\x10\n\x0e_battery_level\"D\n\x17\x45nOceanPacketCollection\x12)\n\x07packets\x18\x01 \x03(\x0b\x32\x18.aruba.iot.EnOceanPacketb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.enocean_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENOCEANPACKET']._serialized_start=36
  _globals['_ENOCEANPACKET']._serialized_end=455
  _globals['_ENOCEANPACKETCOLLECTION']._serialized_start=457
  _globals['_ENOCEANPACKETCOLLECTION']._serialized_end=525
# @@protoc_insertion_point(module_scope)
