# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/wifi.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protos/wifi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/wifi.proto\x12\taruba.iot\"\xe4\x02\n\nWiFiPacket\x12\x12\n\ndevice_mac\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0c\n\x04rssi\x18\x03 \x01(\x05\x12\x0c\n\x04ssid\x18\x04 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x05 \x01(\x05\x12\x13\n\x06\x61p_mac\x18\x06 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65vice_name\x18\x07 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08\x64istance\x18\x08 \x01(\x02H\x02\x88\x01\x01\x12\x15\n\x08security\x18\t \x01(\tH\x03\x88\x01\x01\x12\x16\n\tfrequency\x18\n \x01(\x05H\x04\x88\x01\x01\x12\x13\n\x06vendor\x18\x0b \x01(\tH\x05\x88\x01\x01\x12\x19\n\x0csignal_level\x18\x0c \x01(\x05H\x06\x88\x01\x01\x42\t\n\x07_ap_macB\x0e\n\x0c_device_nameB\x0b\n\t_distanceB\x0b\n\t_securityB\x0c\n\n_frequencyB\t\n\x07_vendorB\x0f\n\r_signal_level\">\n\x14WiFiPacketCollection\x12&\n\x07packets\x18\x01 \x03(\x0b\x32\x15.aruba.iot.WiFiPacketb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.wifi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFIPACKET']._serialized_start=33
  _globals['_WIFIPACKET']._serialized_end=389
  _globals['_WIFIPACKETCOLLECTION']._serialized_start=391
  _globals['_WIFIPACKETCOLLECTION']._serialized_end=453
# @@protoc_insertion_point(module_scope)
